# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lastLine',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
