# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20151215_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('History', 'History'), ('Math', 'Math'), ('Geography', 'Geography'), ('General', 'General')], max_length=200),
        ),
    ]
