# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20151216_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='firstLine',
            new_name='first_line',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lastLine',
            new_name='last_line',
        ),
    ]
